version: "3.3"
services:
  node:
    container_name: costs-backend
    build: .
    networks:
      - costs-backend-net
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    container_name: costs-mongo
    image: mongo:4.1.5-xenial
    networks:
      - costs-backend-net
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: costs
networks:
  costs-backend-net:
    driver: bridge
